version: 2.0
jobs:
  build:
    docker:
      - image: cimg/go:1.14
    steps:
      - checkout
      - run:
          name: "Install lint and format tools"
          command: |
            GO111MODULE=off go get mvdan.cc/gofumpt/gofumports
            GO111MODULE=off go get -u golang.org/x/lint/golint
            GO111MODULE=off go get honnef.co/go/tools/...
      - run:
          name: format
          command: ./build/fmt && git diff --exit-code
      - run:
          name: lint
          command: ./build/lint
      - run:
          name: test
          command: go test -v ./...